// export const LOAD_INITIAL_DATA = "LOAD_INITIAL_DATA";
/* QUIZ ACTIONS */
export const START_QUIZ = "START_QUIZ";
export const ANSWER_CORRECT = "ANSWER_CORRECT";
export const ANSWER_INCORRECT = "ANSWER_INCORRECT";
/* DECK ACTIONS */
export const CREATE_QUESTION = "CREATE_QUESTION";
export const CREATE_DECK = "CREATE_DECK";
